#ifndef __INCLUDES_H__
#define __INCLUDES_H__

#include <C8051F120.H>
#include <STRING.H>
#include <math.h>
#include "types.h"
#include "config.h"
#include "miscellaneous.h"
#include "timer.h"
#include "uart.h"
#include "Oscillator.h"
#include "PORT.h"
#include "IE.h"
#include "SMBus.h"
#include "ADC7714.h"
#include "SPI.h"
#include "ADC.h"
#include "VoltageReference.h"
#include "Comparator.h"
#include "DeviceStatus.h"
#include "InitAllDevices.h"
#include "IE.h"
#include "fuzzycontrol.h"

#endif
